spring.application.name=workshop-management-system

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/workshop_management_system}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=BINARY
spring.jpa.properties.hibernate.default_batch_fetch_size=25

spring.flyway.enabled=true
app.seed.enabled=false

app.supplier.base-url=${SUPPLIER_BASE_URL:http://localhost:8089}
app.supplier.connect-timeout=${SUPPLIER_CONNECT_TIMEOUT:2s}
app.supplier.read-timeout=${SUPPLIER_READ_TIMEOUT:5s}
app.supplier.api-key=${SUPPLIER_API_KEY:}
app.security.jwt.secret=${APP_SECURITY_JWT_SECRET:local-development-only-default-secret-please-rotate-in-any-real-deployment}

springdoc.swagger-ui.path=/swagger-ui.html
